//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAW.FinalProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostReport
    {
        public int Id_Report { get; set; }
        public Nullable<int> Id_User { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> Id_SubCategory { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
